// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sbbwdxczbtnlnjooakfe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNiYndkeGN6YnRubG5qb29ha2ZlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc4MjgyMTEsImV4cCI6MjA3MzQwNDIxMX0.GMO6UVKAF_kyH8TrM7r1S89fhjFBYQdV6_faIMNMls4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});